### ISSUE TITLE
ios에서는 안되는건가요?

### ISSUE THREAD

**Issue by tgkei** [bperhaps/Recovering-KakaoTalk-Expired-Files#2]
IOS에서는 카카오 캐시 관리가 다른가요? 아이폰 연결해서 cache 폴더 찾아서 하려는데 ios 같은 경우엔 DCIM만 접근 가능해서 내부 카카오 폴더를 찾을 수가 없는데 혹시 관련해서 해결 방법을 아시나요?

**Comment by bperhaps** [comment]
제가 알기로는 IOS같은 경우 앱 데이터에 접근이 불가능 한걸로 알고 있습니다.
